### ISSUE TITLE
Doesn't works at macOs Mojace

### ISSUE THREAD

**Issue by salerpsan** [meqabayt/franz-recipe-asana#2]
Hi!

The recipe doesn't work, I followed up the instructions creating the folder and unzipping the recipe but at restart doesn't appear asana.
http://prntscr.com/meeta4

Thank you!

**Comment by ghost** [comment]
> Hi!
> 
> The recipe doesn't work, I followed up the instructions creating the folder and unzipping the recipe but at restart doesn't appear asana.
> http://prntscr.com/meeta4
> 
> Thank you!

change the name to "franz-recipe-asana", drop the master at the end.

**Comment by meqabayt** [comment]
@mustasj change the name to "franz-recipe-asana", drop the master at the end.
